games/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

                       url(r'^$',
                           views.games_index,
                           name='games_index'),

                       
                       url(r'^(?P<game_id>\d+)/$',
                           views.game_detail,
                           name='game_detail'),

]

s3/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import TemplateView

from games import views


urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^bios/', include('bios.urls')),
    url(r'^competitions/', include('competitions.urls')),
    url(r'^dates/', include('dates.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^games/', include('games.urls')),
    url(r'^places/', include('places.urls')),
    url(r'^organizations/', include('organizations.urls')),
    url(r'^sources/', include('sources.urls')),
    url(r'^teams/', include('teams.urls')),
    url(r'^transactions/', include('transactions.urls')),
]

stats/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
]

teams/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

                       url(r'^$',
                           views.team_index,
                           name='team_index'),


                       url(r'^az/(?P<fragment>.+)/$',
                           views.team_name_fragment,
                           name='team_name_fragment'),

                       url(r'^(?P<team_slug>[a-z0-9-]+)/$',
                           views.team_detail,
                           name='team_detail'),

                       url(r'^(?P<team_slug>[a-z0-9-]+)/games/$',
                           views.team_games,
                           name='team_games'),

                       url(r'^(?P<team_slug>[a-z0-9-]+)/stats/$',
                           views.team_stats,
                           name='team_stats'),


]

stats/models.py
from django.db import models

from bios.models import Bio
from competitions.models import Competition, Season
from games.models import Game
from sources.models import Source
from teams.models import Team


class StandingStat(models.Model):

    # Should these be in standing? Probably not.
    # Probably should merge standing into here.
    # plus_minus should be a method? Probably not.
    plus_minus = models.IntegerField(null=True, blank=True)
    goals_for = models.IntegerField(null=True, blank=True)
    goals_against = models.IntegerField(null=True, blank=True)

    games = models.IntegerField(null=True, blank=True)
    wins = models.IntegerField(null=True, blank=True)
    ties = models.IntegerField(null=True, blank=True)
    losses = models.IntegerField(null=True, blank=True)

            
    def win_percentage(self):
        if not self.games:
            return None
        ties = self.ties or 0
        return (self.wins + .5 * ties) / self.games

    def win_percentage_100(self):
        if self.win_percentage() is None:
            return None
        return self.win_percentage() * 100


    class Meta:
        abstract = True



class AbstractStat(StandingStat):

    #game = models.ForeignKey(Game, null=True)
    #player = models.ForeignKey(Bio, null=True)
    #team = models.ForeignKey(Team, null=True)
    #competition = models.ForeignKey(Competition, null=True)
    #season = models.ForeignKey(Season, null=True)

    #position = models.CharField(max_length=255, null=True)
    # Position should probably be a ForeignKey to Position.


    games_started = models.IntegerField(null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    minutes = models.IntegerField(null=True, blank=True)

    goals = models.IntegerField(null=True, blank=True)
    own_goals = models.IntegerField(null=True, blank=True)
    assists = models.IntegerField(null=True, blank=True)
    shots = models.IntegerField(null=True, blank=True)
    shots_on_goal = models.IntegerField(null=True, blank=True)

    fouls_committed = models.IntegerField(null=True, blank=True)
    fouls_suffered = models.IntegerField(null=True, blank=True)
    yellow_cards = models.IntegerField(null=True, blank=True)
    red_cards = models.IntegerField(null=True, blank=True)

    source = models.ForeignKey(Source, null=True)

    class Meta:
        abstract = True


    def shooting_percentage(self):
        return self.goals / float(self.asists)


    def goals_per_90(self):
        if self.minutes == 0:
            return 0
        return 90 * self.goals / float(self.minutes)


    def assists_per_90(self):
        if self.minutes == 0:
            return 0
        return 90 * self.goals / float(self.minutes)


    def goals_assists_per_90(self):
        return self.goals_per_90() + self.assists_per_90()


    def plus_minus_per_90(self):
        if not self.minutes:
            return 0
        return 90 * self.plus_minus / float(self.minutes)


    def goal_proportion(self):
        """
        Proportion of all game goals that a player was involved in.
        """
        return self.goals / float(self.goals_for)



    def partnerships(self, competition, season):
        stats = Stat.objects.filter(competition=competition, season=season)
        teams = set([e[0] for e in stats.values_list('team')])

        l = []
        for team_id in teams:
            team = Team.objects.get(id=team_id)
            tstats = stats.filter(team=team_id).exclude(goals=None).order_by('-goals')
            pair = tstats[:2]
            goals = tstats[0].goals + tstats[1].goals
            t = (goals, competition, season, team, tstats[0].player, tstats[1].player)
            l.append(t)
        return l




class CareerStat(AbstractStat):
    # Should rename player person?
    player = models.ForeignKey(Bio)


class CompetitionStat(AbstractStat):
    player = models.ForeignKey(Bio)
    competition = models.ForeignKey(Competition)


class TeamStat(AbstractStat):
    player = models.ForeignKey(Bio)
    team = models.ForeignKey(Team)


class SeasonStat(AbstractStat):
    player = models.ForeignKey(Bio)
    competition = models.ForeignKey(Competition) # Redundancy
    season = models.ForeignKey(Season)


class TeamCompetitionStat(AbstractStat):
    player = models.ForeignKey(Bio)
    competition = models.ForeignKey(Competition)
    team = models.ForeignKey(Team)


class Stat(AbstractStat):
    player = models.ForeignKey(Bio)
    competition = models.ForeignKey(Competition) # Redundancy
    season = models.ForeignKey(Season)
    team = models.ForeignKey(Team)

    def __str__(self):
        return u"%s: %s/%s/%s" % (self.player, self.competition, self.season.name, self.team)


class GameStat(AbstractStat):
    player = models.ForeignKey(Bio)
    game = models.ForeignKey(Game)
    team = models.ForeignKey(Team)

    age = models.FloatField(null=True) # Age in years at the time of game.
    on = models.IntegerField(null=True)
    off = models.IntegerField(null=True)

    # What order the player is the lineup. (Matt Reis, Avery John, Michael Parkhurst) -> Michael Parkhurst, 3
    order = models.IntegerField(null=True)

    result = models.CharField(max_length=5)


    class Meta:
        ordering = ('game', 'order', 'on', '-id' )
        pass


    def score_or_result(self):
        if self.team == self.game.team1:
            return self.game.score_or_result()
        else:
            return self.game.reverse_score_or_result()

    @property
    def goal_differential(self):
        try:
            return self.goals_for - self.goals_against
        except:
            return None

    def opponent(self):
        if self.team == self.game.team1:
            return self.game.team2
        else:
            return self.game.team1

    def team_original_name(self):
        if self.team == self.game.team1:
            return self.game.team1_original_name
        else:
            return self.game.team2_original_name

    def opponent_original_name(self):
        if self.team == self.game.team1:
            return self.game.team2_original_name
        else:
            return self.game.team1_original_name

teams/models.py
import datetime

from django.db import models
from django.template.defaultfilters import slugify

from places.models import City



class AbstractTeamManager(models.Manager):
    """
    An abstract Team Manager.
    """

    def recent_games(self, delta=datetime.timedelta(days=100)):
        """
        Returns a queryset of games played within a given timedelta.
        """
        since = datetime.date.today() - delta
        return self.get_queryset().filter(date__gte=since)

    def team_dict(self):
        """
        A dict mapping a team's name and short name to an id.
        """
        d = {}
        for e in self.get_queryset():
            d[e.name] = e.id
            d[e.short_name] = e.id
        return d

    def duplicate_slugs(self):
        """
        Returns all teams with duplicate slugs.
        """
        # Used to find problem teams.
        d = defaultdict(list)
        for e in self.get_queryset():
            d[e.slug].append(e.name)
        return [(k, v) for (k, v) in d.items() if len(v) > 1]

            
    def find(self, name, create=False):
        """
        Given a team name, determine the actual team.
        """
        # This seems to duplicate alias functionality that is implemented in soccerdata.
        # Also, this looks a lot more time-consuming.

        #from soccer.teams.aliases import mapping
        teams = Team.objects.filter(name=name)
        if teams:
            return teams[0]

        teams = Team.objects.filter(short_name=name)
        if teams:
            return teams[0]

        if create:

            try:
                print("Creating team {}".format(name))
            except:
                print("Created a team.")

            team = Team.objects.create(
                name=name, 
                short_name=name, 
                )
            return team
        else:
            # Don't want to be creating teams all the time.
            raise



class TeamManager(AbstractTeamManager):
    """
    Normal Team Manager used for Team.objects.
    """


class Team(models.Model):
    """
    A collection of players for a competition.
    """
    # Squads for, e.g. Champions League, World Cup?
    # Rolling roster for any team.
    # retirements.


    name = models.CharField(max_length=200, unique=True)

    # Affiliate team. e.g.
    # Portland Timbers Reserves -> Portland Timbers (reserve -> main)
    # Chicago Fire Select -> Chicago Fire (? affiliation)
    # United States -> United States U-20 (youth team)
    affiliate = models.ForeignKey('self', null=True)

    # Let's get rid of short name! It's really just another alias.
    # No way, it's useful when you want to display a better name.
    # Let's just be clear that it's very optional.
    short_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=100, unique=False)

    founded = models.DateField(null=True)
    dissolved = models.DateField(null=True)

    city = models.ForeignKey(City, null=True, blank=True)
    #city = models.CharField(max_length=255)

    # Have some virtual teams from USMNT drafts.
    real = models.BooleanField(default=True)
    defunct = models.BooleanField(default=False)
    notes = models.TextField(blank=True)

    international = models.BooleanField(default=False)

    objects = TeamManager()
    #defuncts = DefunctTeamManager()
    #reals = RealTeamManager()

    #awards = generic.GenericRelation('awards.AwardItem')


    class Meta:
        ordering = ('short_name',)

    def __str__(self):
        return self.short_name


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.short_name)
            
        super(Team, self).save(*args, **kwargs)



    def game_set(self):
        from games.models import Game
        return Game.objects.filter(models.Q(team1=self) | models.Q(team2=self))






class TeamAlias(models.Model):        
    team = models.ForeignKey(Team)
    name = models.CharField(max_length=200, unique=True)
    
    start = models.DateField()
    end = models.DateField()

    class Meta:
        ordering = ('start',)


    def start_text(self):
        if self.start.month == 1 and self.start.day == 1:
            return self.start.year
        else:
            return self.start
    

    def end_text(self):
        if self.end.month == 12 and self.end.day == 31:
            return self.end.year
        else:
            return self.end
    

games/views.py
from collections import defaultdict, Counter

from django.shortcuts import render, get_object_or_404

from teams.models import Team
from .models import Game, GameSource



def homepage(request):
    """
    Homepage
    """

    #team = Team.objects.get(slug='united-states')
    #games = Game.objects.team_filter(team).order_by("-date").exclude(date=None)[:20]
    games = Game.objects.order_by("-date").exclude(date=None)[:20]

    context = {
        'games': games,
        }

    return render(request, 
                  "games/homepage.html",
                  context)


def games_index(request):
    # Add a paginator.
    # This is probably unnecesary.
    # Consider turning into a games analysis page.
    # Home/Away advantage, graphs, etc.
    
    games = Game.objects.order_by("-date").exclude(date=None)
    game_count = games.count()

    by_year = Counter([e.year for e in games.values_list('date', flat=True)])

    #gd = defaultdict(int)
    #ceiling = 8
    #for game in games.exclude(home_team=None).exclude(team1_score=None).exclude(team2_score=None):
    #    gd[(min(game.home_score(), ceiling), min(game.away_score(), ceiling))] += 1

    context = {
        'games': games,
        'game_count': game_count,
        'games_by_year': json.dumps(sorted(by_year.items())),
        'goal_distribution': json.dumps(gd),
        }

    return render(request, 
                  "games/index.html",
                  context)


def game_detail(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    context = {
        'game': game,
        #'goals': game.goal_set.order_by('minute'),
        'game_sources': GameSource.objects.filter(game=game),

        }
    return render(request, 
                              "games/detail.html",
                              context)
                              

teams/templates/teams/detail.html
{% extends "base.html" %}
{% load datum_or_none %}

{% load stats %}
{% load games %}

{% comment %}
{% load standings %}

{% endcomment %}

{% block title %}{{ team.name }}{% endblock %}
{% block metadescription %}Game results, statistics, awards and more for {{ team.name }}{% endblock %}

{% block content %}

<div id="team_info">

<div id="team_logo"></div>

<div id="team_data">
<div>{{ team.name }}</div>
</div>

{% if team.teamalias_set.exists %}
<p class="small">also known as: 
{% for alias in team.teamalias_set.all %}
{{ alias.name }} ({{ alias.start_text }} to {{ alias.end_text }}) {% if not forloop.last %},{% endif %}
{% endfor %}
</p>
{% endif %}


</div>


<div id="tab_block">
<ul id="tabs"></ul>
</div>


<div id="tab_wrapper">


<div tab="summary">
</div>




{% if competition_standings or league_standings %}
<div tab="standings">
{% comment %}
{% standings_table competition_standings 'team,season' %}
{% standings_table league_standings 'team' %}
{% endcomment %}

</div>
{% endif %}

{% if game_leaders or goal_leaders %}
<div tab="stats">

<div>
<a href="{% url 'team_stats' team.slug %}">all stats</a>
</div>



{% if game_leaders %}
<div class="col">
<div>game leaders</div>
{% stats_table game_leaders 'team,competition,season' 15 %}
</div>
{% endif %}

{% if goal_leaders %}
<div class="col">
<div>goal leaders</div>
{% stats_table goal_leaders 'team,competition,season' 15 %}
</div>
{% endif %}

</div>
{% endif %}



<div tab="games">
<a href="{% url 'team_games' team.slug %}">all games</a>
{# {% games_table recent_games %} #}
</div>

<div tab="games">
<a href="{% url 'team_stats' team.slug %}">all stats</a>
{# {% games_table recent_games %} #}
</div>

<table>
{% for transaction in transactions %}
<tr>
  <td><a href="{% url 'transaction_detail' transaction.id %}">{{ transaction.id }}</a></td>
  <td>{{ transaction.ttype }}</td>
  <td><a href="{% url 'person_detail' transaction.person.slug %}">{{ transaction.person }}</a></td>
</tr>
{% endfor %}
</table>



{% endblock %}

teams/templates/teams/games.html
{% extends "base.html" %}
{% load datum_or_none %}
{% load games %}

{% block title %}{{ team.name }} All-time Game Results{% endblock %}
{% block metadescription %}All-time game results for {{ team.name }}{% endblock %}

{% block content %}


{% if games %}
<div tab="games">
{% games_table games %}
</div>
{% endif %}


<script>
calendarChart("#calendar-chart", {{ calendar_data|safe }})
</script>



{% endblock %}

teams/templates/teams/index.html
{% extends "base.html" %}

{% block title %}team directory{% endblock %}

{% block content %}



<ul>
  {% for letter, standings in name_dict.items %}
  <li>
    <a class="letter_link" href="{% url 'team_name_fragment' letter %}">{{ letter }}</a>
    {% for standing in standings %}
    <a class="item" href="{% url 'team_detail' standing.team.slug %}">{{ standing.team }}</a>{% if forloop.last %}...{% else %} |{% endif %}
    {% endfor %}
  </li>
  {% endfor  %}
</ul>

{% comment %}
<ul>
  {% for letter, teams in name_dict.items %}
  {% if teams.exists %}
  <li class="alphabet">
    <a class="letter_link" href="{% url 'team_name_fragment' letter %}">{{ letter }}</a>
    {% for team in teams %}
    <a class="item" href="{% url 'team_detail' team.slug %}">{{ team }}</a>{% if forloop.last %}...{% else %} |{% endif %}
    {% endfor %}
  </li>
  {% endif %}
  {% endfor %}
</ul>
{% endcomment %}


{% endblock %}

teams/templates/teams/stats.html
{% extends "base.html" %}
{% load datum_or_none %}
{% load games %}
{% load stats %}

{% block title %}{{ team.name }} All-time Game Results{% endblock %}
{% block metadescription %}All-time game results for {{ team.name }}{% endblock %}

{% block content %}

{% stats_table team.teamstat_set.all 'team' %}





{% endblock %}